language: php

services:
  - mysql

php:
  - 7.0.8
  - 7.1

cache:
  yarn: true

before_script:
  - printf "\n" | pecl install imagick
  - sudo apt-get install -y pngquant
  - composer install
  - echo "USE mysql;\nUPDATE user SET password=PASSWORD('battle218pw') WHERE user='root';\nFLUSH PRIVILEGES;\n" | mysql -u root

  # Yarn
  - sudo apt-key adv --fetch-keys http://dl.yarnpkg.com/debian/pubkey.gpg
  - echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq yarn
  - yarn install

script:
  - yarn lint
  - cp bgaproject.yml.dist bgaproject.yml
  - composer compile-images > /dev/null
  - composer clean
  - composer build
  - composer bga-validate
  - composer check-styles
  - composer test