language: php

services:
  - mysql

php:
  - 7.0.8
  - 7.1

before_script:
  - printf "\n" | pecl install imagick-3.4.2
  - sudo apt-get install -y pngquant
  - composer install
  - echo "USE mysql;\nUPDATE user SET password=PASSWORD('battle218pw') WHERE user='root';\nFLUSH PRIVILEGES;\n" | mysql -u root

script:
  - cp bgaproject.yml.dist bgaproject.yml
  - bin/bfh compile-images > /dev/null
  - bin/bgawb validate
  - vendor/bin/phpcs --standard=PSR2 --tab-width=4 --ignore=src/BGAWorkbench/Stubs,tests/bootstrap.php -q -p tests src
  - vendor/bin/phpunit