language: php

services:
  - mysql

php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1

before_script:
  - composer install
  - echo "USE mysql;\nUPDATE user SET password=PASSWORD('battle218pw') WHERE user='root';\nFLUSH PRIVILEGES;\n" | mysql -u root

script:
  - bin/bgawb validate
  - vendor/bin/phpunit