language: php

services:
  - mysql

php:
  - 7.0.8
  - 7.1

before_script:
  - printf "\n" | pecl install imagick
  - sudo apt-get install -y pngquant
  - composer install
  - echo "USE mysql;\nUPDATE user SET password=PASSWORD('battle218pw') WHERE user='root';\nFLUSH PRIVILEGES;\n" | mysql -u root

script:
  - cp bgaproject.yml.dist bgaproject.yml
  - composer compile-images > /dev/null
  - composer clean
  - composer build
  - composer bga-validate
  - composer check-styles
  - composer test