language: php

services:
  - mysql

php:
  - 5.6
  - 7.0
  - 7.1

before_script:
  - composer install
  - echo "USE mysql;\nUPDATE user SET password=PASSWORD('battle218pw') WHERE user='root';\nFLUSH PRIVILEGES;\n" | mysql -u root

script:
  - bin/bgawb validate
  - phpcs --standard=PSR2 --tab-width=4 --ignore=src/BGAWorkbench/Stubs,tests/bootstrap.php -q -p tests src
  - vendor/bin/phpunit