name: Test

on:
  push:
    branches: master

jobs:
  deploy:
    name: Test on PHP ${{ matrix.php_version }}
    strategy:
      matrix:
        php_version:
          - 7.1
#          - 7.2
#          - 7.3
#          - 7.4

    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
      - name: "System update"
        run: |
          sudo apt-key adv --fetch-keys http://dl.yarnpkg.com/debian/pubkey.gpg
          echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
          sudo apt-get update -qq
      - name: "Install mysql"
        run: sudo apt install -y mysql-server
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php_version }}
          tools: pecl
          extensions: imagick
      - name: "PHP deps"
        run: |
          sudo apt install -y pngquant
          composer install
      - name: "Install Yarn"
        run: |
          sudo apt install -y -qq yarn
          yarn install
      - name: "Setup BGA Project"
        run: cp bgaproject.yml.github.dist bgaproject.yml
      - name: Check JS
        run: yarn lint:check
      - name: Run tests
        run: |
          composer compile-images > /dev/null
          composer clean
          composer build
          composer bga-validate
          composer check-styles
          composer test
